[package]
name = "esercizio9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="esercizio9"
path= "src/lib.rs"
[dependencies]
rand = "0.9.0-alpha.1"
